#!/bin/sh
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE DATABASE $APP_DATABASE_DBNAME WITH ENCODING 'UTF8';"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE USER $APP_DATABASE_USER WITH ENCRYPTED PASSWORD '$APP_DATABASE_PASS';"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "GRANT ALL PRIVILEGES ON DATABASE $APP_DATABASE_DBNAME TO $APP_DATABASE_USER;"
psql -v ON_ERROR_STOP=1 --username "$APP_DATABASE_USER" -c "CREATE SCHEMA $APP_DATABASE_SCHEMA" $APP_DATABASE_DBNAME;
