FROM gradle:5.5-jdk8 as builder
WORKDIR /builder
ADD . /builder
RUN gradle --no-daemon -p product build -x test

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=builder /builder/product/build/libs/product-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "product-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080